name: Continuous Integration (CI)

# Trigger the workflow on push and pull request events to the 'main' branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # The runner environment (e.g., ubuntu-latest, windows-latest, macos-latest)

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the code in the repository

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Set the Python version for the environment

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies from the requirements file

    - name: Run tests
      run: |
        # If using pytest, run the tests
        pytest  # Adjust based on your test framework, like unittest or others

    - name: Lint code
      run: |
        # If using flake8 for linting, run the linter
        flake8 .  # Lint all files in the repository

    - name: Upload coverage report
      if: success()  # Upload coverage if tests pass
      run: |
        # If using coverage.py, upload the report to a service like Codecov
        coverage report
        coverage html  # Generate HTML coverage report
